from typing import Any
import pandas as pd
import numpy as np

class IReducer:
    def fit(self, X: pd.DataFrame | np.ndarray) -> "IReducer": ...
    def transform(self, X: pd.DataFrame | np.ndarray) -> np.ndarray: ...
    def fit_transform(self, X: pd.DataFrame | np.ndarray) -> np.ndarray: ...
