[tool.poetry]
name = "mlops-pipeline"
version = "0.1.0"
description = "Pipeline MLOps modular"
authors = ["Mercado Libre MLOps Team"]
packages = [
  { include = "eda_univariado", from = "src" },
  { include = "ingestion", from = "src" },
  { include = "validation_inference", from = "src" },
  { include = "data_ingestion_validation", from = "src" },
  { include = "feature_engineering", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "*"
pyodbc = "*"
psycopg2-binary = "*"
databricks-sql-connector = "*"
mlflow = "*"
dvc = "*"
pandera = "*"
great-expectations = "*"
evidently = "*"
nannyml = "*"
pydeequ = "*"
pyyaml = "*"
scikit-learn = "*"

[tool.poetry.group.dev.dependencies]
ruff = "*"
black = "*"
mypy = "*"
pytest = "*"
pytest-cov = "*"

[tool.ruff]
line-length = 88

[tool.black]
line-length = 88

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-q"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
