FROM mcr.microsoft.com/azureml/curated/minimal-ubuntu20.04-py38-cpu-inference:latest

ENV APP_HOME=/app
WORKDIR $APP_HOME

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY src/inference/online ./src/inference/online
COPY src/monitoring ./src/monitoring
CMD ["uvicorn", "src.inference.online.app:app", "--host", "0.0.0.0", "--port", "8080"]
